# Generated by Django 4.2.1 on 2023-06-16 07:53

from django.db import migrations, models
import restaurantapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name1', models.CharField(default='', max_length=150)),
                ('Last_name1', models.CharField(default='', max_length=30)),
                ('NO_of_persons1', models.IntegerField(default=0)),
                ('phone_number1', models.TextField(default='', max_length=40)),
                ('mail1', models.TextField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurantapp.models.getFileName)),
            ],
        ),
    ]
