# Generated by Django 4.2.1 on 2023-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datastore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name1', models.CharField(default='', max_length=150)),
                ('Last_name1', models.CharField(default='', max_length=30)),
                ('NO_of_persons1', models.IntegerField(default=0)),
                ('phone_number1', models.TextField(default='', max_length=40)),
                ('mail1', models.TextField(default='', max_length=40)),
            ],
        ),
    ]
