# Generated by Django 4.2.1 on 2023-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_datastore'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='Date1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datastore',
            name='Time1',
            field=models.DateTimeField(null=True),
        ),
    ]
