# Generated by Django 4.2.1 on 2023-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_datastore_date1_datastore_time1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='Date1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='Time1',
            field=models.TimeField(null=True),
        ),
    ]
